# .github/workflows/reusable-react-s3-deploy.yml
# Workflow name
name: Reusable React Build and S3 Deploy (env from secrets)

# --- Trigger ---
# Makes this workflow reusable by other workflows
on:
  workflow_call:
    # --- Inputs ---
    inputs:
      aws_region:
        description: 'AWS region for the S3 bucket'
        required: true
        type: string
      branch_name:
        description: 'The branch name triggering the deployment'
        required: true
        type: string
      repo_name:
        description: 'The repository name'
        required: true
        type: string
      build_output_dir:
        description: 'Path to the built static files directory'
        required: false
        type: string
        default: './build/'
      node_version:
        description: 'Node.js version for build'
        required: false
        type: string
        default: '18.x'
      install_command:
        description: 'Command to install dependencies'
        required: false
        type: string
        default: 'npm ci'
      build_command:
        description: 'Command to build the React application'
        required: false
        type: string
        default: 'npm run build'
      secrets_to_ignore:
        description: 'Space-separated list of GitHub secret names to NOT include in the .env file'
        required: false
        type: string
        default: "AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY GITHUB_TOKEN github_token"

    # --- Secrets ---
    secrets:
      AWS_ACCESS_KEY_ID:
        description: 'AWS Access Key ID for S3 deployment'
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: 'AWS Secret Access Key for S3 deployment'
        required: true

# --- Jobs ---
jobs:
  build-and-deploy:
    name: Build and Deploy to S3
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: 'npm'

      # Step 3: Create .env file from inherited secrets (using env + filtering)
# Step 3: Create .env file from inherited secrets (using env + filtering)
      - name: Create .env file
        env: ${{ secrets }}
        run: |
          # --- START DEBUG: Print all available environment variables ---
          echo "--- Debug: All Environment Variables Available in Step (Sorted Key=Value) ---"
          # Show KEY=value pairs, sorted, to see the raw values
          env | sort
          echo "--- End Debug ---"
          # --- END DEBUG ---

          echo "Generating .env file from inherited secrets..."
          SECRETS_TO_IGNORE_LIST=" ${{ inputs.secrets_to_ignore }} "
          ENV_FILE=".env"
          > "$ENV_FILE" # Create or truncate the .env file
          added_count=0

          env | while IFS='=' read -r key value; do
            # --- ADDED DEBUG: Show exactly what the loop read ---
            echo "Loop Processing Line: Key='${key}' Value='${value}'"

            # --- Filtering Logic ---

            # Filter 1: Check against the ignore list
            if echo "$SECRETS_TO_IGNORE_LIST" | grep -q " $key "; then
              echo "DEBUG Action: Ignored '$key' via Filter 1 (Ignore List)" # Specify reason
              continue
            fi

            # # Filter 2: Check against common system/GitHub Actions variables (Still Commented Out)
            # if [[ "$key" =~ ^(HOME|PATH|PWD|USER|CI|RUNNER_|GITHUB_|ACTIONS_|INPUT_|AWS_REGION|AWS_DEFAULT_REGION|NODE_VERSION)$ ]]; then
            #   echo "DEBUG Action: Ignored '$key' via Filter 2 (System/Actions Var)" # Specify reason
            #   continue
            # fi

            # Filter 3: Explicitly ignore AWS keys again
            if [[ "$key" == "AWS_ACCESS_KEY_ID" || "$key" == "AWS_SECRET_ACCESS_KEY" ]]; then
              echo "DEBUG Action: Ignored '$key' via Filter 3 (AWS Key)" # Specify reason
              continue
            fi

            # Filter 4: (Removed)

            # --- Add to .env ---
            # This line should now execute for TEST_SECRET if it reaches here
            echo "DEBUG Action: Adding variable to .env: $key" # Log action
            printf '%s="%s"\n' "$key" "$value" >> "$ENV_FILE"
            added_count=$((added_count + 1))

          done # End of while loop

          echo "Finished generating .env file. Added $added_count variables."
          if [ "$added_count" -gt 0 ]; then
            echo "Generated .env content (sensitive values masked):"
            cat "$ENV_FILE" | sed -E 's/(PASSWORD|API_KEY|SECRET|TOKEN)=.*/\1=****/'
          else
            echo "No variables added to .env file after filtering."
          fi
      # Step 4: Install project dependencies
      - name: Install dependencies
        run: ${{ inputs.install_command }}

      # Step 5: Build the React application
      - name: Build React application
        run: ${{ inputs.build_command }}

      # Step 6: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}

      # Step 7: Deploy static files to S3 bucket
      - name: Deploy static site to S3 bucket
        run: |
          echo "Preparing deployment..."
          echo "Using build output directory: ${{ inputs.build_output_dir }}"
          BRANCH_NAME=$(echo "${{ inputs.branch_name }}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g')
          REPO_NAME_LOWER=$(echo "${{ inputs.repo_name }}" | tr '[:upper:]' '[:lower:]')
          REGION_LOWER=$(echo "${{ inputs.aws_region }}" | tr '[:upper:]' '[:lower:]')
          BUCKET_NAME="${BRANCH_NAME}-${REPO_NAME_LOWER}-${REGION_LOWER}-static-s3"
          echo "Target S3 Bucket: s3://${BUCKET_NAME}"
          if [ ! -d "${{ inputs.build_output_dir }}" ]; then
            echo "Error: Build output directory '${{ inputs.build_output_dir }}' not found!"
            exit 1
          fi
          aws s3 sync ${{ inputs.build_output_dir }} "s3://${BUCKET_NAME}" --delete
          echo "Deployment to s3://${BUCKET_NAME} completed."